Manitouage1/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manitouage1.Models
{
    public class JobPosting
    {
        [Key]
        public int jobPostingId { get; set; }

        [Required]
        public string jobNumber { get; set; }

        [Required]
        public string jobTitle { get; set; }

        [Required]
        public string jobType { get; set; }

        [AllowHtml]
        [Required]
        public string jobDescription { get; set; }

        [Required]
        public string salary { get; set; }

        [Required]
        public DateTime closingDate { get; set; }

        [ForeignKey("Department")]
        public int departmentId { get; set; }
        public string departmentName { get; set; }

        public virtual Department Department { get; set; }

    }

    public class JobPostingDto
    {
        [DisplayName("Job Posting ID")]
        public int jobPostingId { get; set; }

        [DisplayName("Job Number")]
        [Required(ErrorMessage = "Please Enter Job Number")]
        public string jobNumber { get; set; }

        [DisplayName("Job Title")]
        [Required(ErrorMessage = "Please Enter Job Title")]
        public string jobTitle { get; set; }

        [DisplayName("Job Type")]
        [Required(ErrorMessage = "Please Enter Job Type")]
        public string jobType { get; set; }

        [DisplayName("Job Description")]
        [Required(ErrorMessage = "Please Enter Job Description")]
        public string jobDescription { get; set; }

        [DisplayName("Salary")]
        [Required(ErrorMessage = "Please Enter Salary")]
        public string salary { get; set; }

        [DisplayName("Closing Date and Time")]
        [Required(ErrorMessage = "Please Enter Closing Date and Time")]
        public DateTime closingDate { get; set; }

        [DisplayName("Department ID")]
        public int departmentId { get; set; }

        [DisplayName("Department Name")]
        public string departmentName { get; set; }
    }
}

Manitouage1/Controllers/JobPostingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Manitouage1.Models;
using Manitouage1.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace Manitouage1.Controllers
{
    public class JobPostingController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static JobPostingController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                UseCookies = false
            };
            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44397/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));


            //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", ACCESS_TOKEN);

        }

        private void GetApplicationCookie()
        {
            string token = "";
           
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }


        // GET: JobPostitng/List
        public ActionResult List()
        {
            ListJobPostings ViewModel = new ListJobPostings();
            ViewModel.isadmin = User.IsInRole("Admin");

            string url = "jobpostingdata/getjobpostings";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<JobPostingDto> SelectedJobPosting = response.Content.ReadAsAsync<IEnumerable<JobPostingDto>>().Result;
                ViewModel.jobpostings = SelectedJobPosting;
                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: JobPosting/Details/5
        public ActionResult Details(int id)
        {
            ShowJobPosting ViewModel = new ShowJobPosting();
            ViewModel.isadmin = User.IsInRole("Admin");

            string url = "jobpostingdata/findjobposting/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            Debug.WriteLine("Details:" + response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into department data transfer object
                JobPostingDto SelectedJobPosting = response.Content.ReadAsAsync<JobPostingDto>().Result;
                ViewModel.jobposting = SelectedJobPosting;


                 url = "jobpostingdata/finddepartmentforjobposting/" + id;
                 response = client.GetAsync(url).Result;
                 DepartmentDto SelectedDepartment = response.Content.ReadAsAsync<DepartmentDto>().Result;
                 ViewModel.department = SelectedDepartment;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: JobPosting/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {

            UpdateJobPosting ViewModel = new UpdateJobPosting();
            //get information about Department
            string url = "departmentdata/getdepartments";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<DepartmentDto> PotentialDepartments = response.Content.ReadAsAsync<IEnumerable<DepartmentDto>>().Result;
            ViewModel.alldepartments = PotentialDepartments;

            return View(ViewModel);
        }

        

        // POST: JobPosting/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(JobPosting JobPostingInfo)
        {
            GetApplicationCookie();

            Debug.WriteLine("Create Post");
            Debug.WriteLine(JobPostingInfo.jobPostingId);
            string url = "jobpostingdata/addjobposting";
            Debug.WriteLine(jss.Serialize(JobPostingInfo));
            HttpContent content = new StringContent(jss.Serialize(JobPostingInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                int jobPostingid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = jobPostingid });
            }
            else
            {
                return RedirectToAction("Error");
            }


        }

        // GET: JobPosting/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            UpdateJobPosting ViewModel = new UpdateJobPosting();

            string url = "jobpostingdata/findjobposting/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            Debug.WriteLine("edit: " + response.StatusCode);
            if (response.IsSuccessStatusCode)
            {

                JobPostingDto SelectedJobPosting = response.Content.ReadAsAsync<JobPostingDto>().Result;
                ViewModel.jobposting = SelectedJobPosting;
                

                 url = "departmentdata/getdepartments";
                 response = client.GetAsync(url).Result;
                 IEnumerable<DepartmentDto> PotentialDepartments = response.Content.ReadAsAsync<IEnumerable<DepartmentDto>>().Result;
                Debug.WriteLine("Jobposting before getDepartment:");

                ViewModel.alldepartments = PotentialDepartments;
               
                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: JobPosting/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, JobPosting JobPostingInfo)
        {
            GetApplicationCookie();

            Debug.WriteLine("Controller Edit: " + JobPostingInfo.jobPostingId);
            string url = "jobpostingdata/updatejobposting/" + id;
            Debug.WriteLine(jss.Serialize(JobPostingInfo));
            HttpContent content = new StringContent(jss.Serialize(JobPostingInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: JobPosting/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "jobpostingdata/findjobposting/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into jobposting data transfer object
                JobPostingDto SelectedJobPosting = response.Content.ReadAsAsync<JobPostingDto>().Result;
                return View(SelectedJobPosting);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: JobPosting/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            GetApplicationCookie();

            Debug.WriteLine("Delete");
            string url = "jobpostingdata/deletejobposting/" + id;
            //post body is empty
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

Manitouage1/Views/JobPosting/Create.cshtml
@model Manitouage1.Models.ViewModels.UpdateJobPosting

@{
    ViewBag.Title = "Create";
}

<div class="col-12 pl-5 pr-5">
    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    <h2 class="mt-3 mb-5">Create Job Posting</h2>

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
    
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.jobNumber, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobposting.jobNumber, new { htmlAttributes = new { @class = "form-control", Name = "jobNumber" } })
                @Html.ValidationMessageFor(model => model.jobposting.jobNumber, "", new { @class = "text-danger", data_valmsg_for = "jobNumber" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.jobTitle, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobposting.jobTitle, new { htmlAttributes = new { @class = "form-control", Name = "jobTitle" } })
                @Html.ValidationMessageFor(model => model.jobposting.jobTitle, "", new { @class = "text-danger", data_valmsg_for = "jobTitle" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.jobType, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" }) 
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobposting.jobType, new { htmlAttributes = new { @class = "form-control", Name = "jobType" } })
                @Html.ValidationMessageFor(model => model.jobposting.jobType, "", new { @class = "text-danger", data_valmsg_for = "jobType" })

            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.jobDescription, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.jobposting.jobDescription, new { @class = "form-control admin", Name = "jobDescription" })
                @Html.ValidationMessageFor(model => model.jobposting.jobDescription, "", new { @class = "text-danger", data_valmsg_for = "jobDescription" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.salary, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobposting.salary, new { htmlAttributes = new { @class = "form-control", Name = "salary" } })
                @Html.ValidationMessageFor(model => model.jobposting.salary, "", new { @class = "text-danger", data_valmsg_for = "salary" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.closingDate, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobposting.closingDate, new { htmlAttributes = new { @class = "form-control", Name = "closingDate" } })
                @Html.ValidationMessageFor(model => model.jobposting.closingDate, "", new { @class = "text-danger", data_valmsg_for = "closingDate" })
            </div>
        </div>
        @*
            <div class="form-group">
                @Html.LabelFor(model => model.departmentId, "departmentId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("departmentId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.departmentId, "", new { @class = "text-danger" })
                </div>
            </div>
        *@

        <div class="form-group row">
            @Html.LabelFor(model => model.jobposting.departmentId, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
            <div class="col-md-10">
                <select name="departmentId">
                    @foreach (var department in Model.alldepartments)
                    {
                        <option value="@department.departmentId">@department.departmentName</option>
                    }
                </select>
            </div>
        </div>
        @*
            <div class="form-group">
                @Html.LabelFor(model => model.departmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.departmentId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.departmentId, "", new { @class = "text-danger" })
                </div>
            </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.departmentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.departmentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.departmentName, "", new { @class = "text-danger" })
                    </div>
                </div>
        *@

        <div class="form-group row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info my-2 my-sm-0" />
            </div>
        </div>
    </div>
}
 </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Manitouage1/Views/JobPosting/DeleteConfirm.cshtml
@model Manitouage1.Models.JobPostingDto

@{
    ViewBag.Title = "DeleteConfirm";
}


<div class="col-12 pl-5 pr-5">
    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    <h2 class="mt-3 mb-3">Delete Confirm</h2>

    <h3 class="mb-5">Are you sure to delete this job posting?</h3>

    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.departmentName)
            </div>

            <div>
                @Html.DisplayFor(model => model.departmentName)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">

                @Html.DisplayNameFor(model => model.jobNumber)
            </div>

            <div>
                @Html.DisplayFor(model => model.jobNumber)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">

                @Html.DisplayNameFor(model => model.jobTitle)
            </div>

            <div>
                @Html.DisplayFor(model => model.jobTitle)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.jobType)
            </div>

            <div>
                @Html.DisplayFor(model => model.jobType)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">

                @Html.DisplayNameFor(model => model.jobDescription)
            </div>

            <div>
                @Html.Raw(Model.jobDescription)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.salary)
            </div>

            <div>
                @Html.DisplayFor(model => model.salary)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.closingDate)
            </div>

            <div>
                @Html.DisplayFor(model => model.closingDate)
            </div>
        </div>
    </div>
    <div class="col-md-12 my-3">
        <div class="row">
            <div class="col-md-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.departmentName)
            </div>

            <div>
                @Html.DisplayFor(model => model.departmentName)
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "JobPosting", new { id = Model.jobPostingId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color mt-3">
            <input type="submit" value="Delete" class="btn btn-info my-2 my-sm-0" />

        </div>
        
    }
</div>

Manitouage1/Views/JobPosting/Details.cshtml
@model Manitouage1.Models.ViewModels.ShowJobPosting
@{
    ViewBag.Title = "Details";
}



<div class="col-12 pl-5 pr-5">
    <div>
        @Html.ActionLink("Back to List", "List")
    </div>
    @if (Model.isadmin)
    {
        <h2 class="mt-3 mb-5">Job Posting Details</h2>
    }

    @if (!Model.isadmin)
    {
        <h2 class="mt-3 mb-5">Opportunities</h2>

        <h4 class="mb-4 font-weight-bold">
            @Html.DisplayFor(model => model.jobposting.jobNumber) - @Html.DisplayFor(model => model.jobposting.jobTitle)
        </h4>


    }
    <div class="row">

        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.jobNumber)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.jobposting.jobNumber)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.jobTitle)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.jobposting.jobTitle)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.jobType)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.jobposting.jobType)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.jobDescription)
                </div>

                <div class="col-md-9">
                    @Html.Raw(Model.jobposting.jobDescription)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.salary)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.jobposting.salary)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.closingDate)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.jobposting.closingDate)
                </div>
            </div>
        </div>
        <div class="col-md-12 my-3">
            <div class="row">
                <div class="col-md-3 font-weight-bold">
                    @Html.DisplayNameFor(model => model.jobposting.departmentName)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.department.departmentId) -  @Html.DisplayFor(model => model.department.departmentName)
                </div>
            </div>
        </div>
    </div>

    @if (Model.isadmin)
    {
        <div class="btn btn-info my-2 my-sm-0 a-white">
            @Html.ActionLink("Edit", "Edit", new { id = Model.jobposting.jobPostingId })

        </div>
    }

    @if (!Model.isadmin)
    {
        @* No one has not done apply for job function so this button goes not redirect to anywhere now*@
        <button class="btn btn-info my-2 my-sm-0" type="submit">
            Apply for this job
        </button>
    }
</div>

Manitouage1/Views/JobPosting/Edit.cshtml
@model Manitouage1.Models.ViewModels.UpdateJobPosting
@{
    ViewBag.Title = "Edit";
}

<div class="col-12 pl-5 pr-5">

    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    <h2 class="mt-3 mb-5">Edit Job Posting</h2>

    @using (Html.BeginForm("Edit", "JobPosting", new { id = Model.jobposting.jobPostingId }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.jobposting.jobPostingId, new { Name = "jobPostingId" })

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.jobNumber, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobposting.jobNumber, new { htmlAttributes = new { @class = "form-control", Name = "jobNumber" } })
                    @Html.ValidationMessageFor(model => model.jobposting.jobNumber, "", new { @class = "text-danger", data_valmsg_for = "jobNumber" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.jobTitle, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobposting.jobTitle, new { htmlAttributes = new { @class = "form-control", Name = "jobTitle" } })
                    @Html.ValidationMessageFor(model => model.jobposting.jobTitle, "", new { @class = "text-danger", data_valmsg_for = "jobTitle" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.jobType, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobposting.jobType, new { htmlAttributes = new { @class = "form-control", Name = "jobType" } })
                    @Html.ValidationMessageFor(model => model.jobposting.jobType, "", new { @class = "text-danger", data_valmsg_for = "jobType" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.jobDescription, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.jobposting.jobDescription, new { @class = "form-control admin", Name = "jobDescription" })
                    @Html.ValidationMessageFor(model => model.jobposting.jobDescription, "", new { @class = "text-danger", data_valmsg_for = "jobDescription" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.salary, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobposting.salary, new { htmlAttributes = new { @class = "form-control", Name = "salary" } })
                    @Html.ValidationMessageFor(model => model.jobposting.salary, "", new { @class = "text-danger", data_valmsg_for = "salary" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.closingDate, htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobposting.closingDate, new { htmlAttributes = new { @class = "form-control", Name = "closingDate" } })
                    @Html.ValidationMessageFor(model => model.jobposting.closingDate, "", new { @class = "text-danger", data_valmsg_for = "closingDate" })
                </div>
            </div>
           
            <div class="form-group row">
                @Html.LabelFor(model => model.jobposting.departmentId, "departmentId", htmlAttributes: new { @class = "control-label col-md-2 font-weight-bold" })
                <div class="col-md-10">
                    <select name="departmentId">
                        @foreach (var department in Model.alldepartments)
                        {

                            <option value="@department.departmentId" @if (department.departmentId == Model.jobposting.departmentId) { <text> selected</text> }>@department.departmentId - @department.departmentName</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-info my-2 my-sm-0" />
                </div>
            </div>
        </div>

    }

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}