Manitouage1/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Manitouage1.Models
{
    public class Donation
    {
        [Key]
        public int donationId { get; set; }

        [Required]
        public string firstName { get; set; }

        [Required]
        public string lastName { get; set; }

        [Required]
        public string email { get; set; }

        public int phoneNumber { get; set; }


        public decimal amount { get; set; }

        //a donation can be made to one event
        [ForeignKey("Event")]
        //if it's null
        public int? EventId { get; set; }
        public virtual Event Event { get; set; }


    }

    public class DonationDto
    {
        [DisplayName("Donation ID")]
        public int donationId { get; set; }

        [DisplayName("First Name")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [DisplayName("Email")]
        public string email { get; set; }

        [DisplayName("Phone")]
        public int phoneNumber { get; set; }

        [DisplayName("Amount")]
        public decimal amount { get; set; }

        [DisplayName("Event Id")]
        public int? EventId { get; set; }

        [DisplayName("Event Name")]
        public string Title { get; set; }


    }
}

Manitouage1/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Manitouage1.Models;
using Manitouage1.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace Manitouage1.Controllers
{

    // Most of the controller code has been referenced from "VarsityMvp, Passion Project and inclass examples"

    public class DonationController : Controller
    {
        //reference my passion project also varsity with auth
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static DonationController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            //Christine comment:: change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44397/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));


        }
        // GET: Donation
        //for views where it links back to list
        public ActionResult Index()
        {
            return View("List");
        }

        //GET: Donation/List
        [HttpGet]
        public ActionResult List()
        {
            //using view model to view donations
            ListDonation ViewModel = new ListDonation();

            //debugging to see if this controller works
            Debug.WriteLine("Here");

            //URL string for browser
            string url = "DonationData/getdonations";

            // Sending HHTP request and getting a http response 
            HttpResponseMessage response = client.GetAsync(url).Result;

            //if the response works show alist of donations 
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<DonationDto> allDonations = response.Content.ReadAsAsync<IEnumerable<DonationDto>>().Result;

                //return View(Donations);

                ViewModel.alldonations = allDonations;
                return View(ViewModel);

            }
            else
            {
                //else the call failed return "error" string 
                return RedirectToAction("Error");
            }


        }

        // GET: Donation/Details/5
        public ActionResult Details(int id)
        {
            //using view model to detail donation by id REFERENCE teamController in varsity w auth
            ShowDonation ViewModel = new ShowDonation();

            //creating a url string
            string url = "DonationData/FindDonation/" + id;

            //sending http request and getting a response back
            HttpResponseMessage response = client.GetAsync(url).Result;

            //if statment:: if the call worked return this else return error
            if (response.IsSuccessStatusCode)
            {
                DonationDto SelectedDonation = response.Content.ReadAsAsync<DonationDto>().Result;
                ViewModel.donation = SelectedDonation;

                //add the get statement for events related to the donations (id is the donation id that we will use to get details)
                //REF VIDEO for week 4 before passion project (git code was harder to understand)
                url = "DonationData/FindEventForDonation" + id;//donation id FYI
                response = client.GetAsync(url).Result;
                EventDto SelectedEvent = response.Content.ReadAsAsync<EventDto>().Result;
                ViewModel.events = SelectedEvent;

                return View(ViewModel);
            }
            else
            {

                return RedirectToAction("Error");

            }
        }

        // GET: Donation/Create
        public ActionResult Create()
        {
            //using view model for add donation.
            //here we want to display a form and a drop down for all events if the user wished to donate to an event
            CreateDonation ViewModel = new CreateDonation();
            //Pulling from AMANDA's eventcontroller for get events
            string url = "EventData/GetEvents";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<EventDto> PotentialEvents = response.Content.ReadAsAsync<IEnumerable<EventDto>>().Result;

            ViewModel.allevents = PotentialEvents;

            return View(ViewModel);
        }

        // POST: Donation/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Donation donationInfo)
        {
            //Debug.WriteLine("THIS IS WORKING!!!");
            // url string we will use to send port request  
            string url = "DonationData/AddDonation";
            //Debug.WriteLine(jss.Serialize(donationInfo));
            HttpContent content = new StringContent(jss.Serialize(donationInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                int donationId = response.Content.ReadAsAsync<int>().Result;
                //in this case we would redirect to list page for user to review the donation posted 
                return RedirectToAction("Details", new { id = donationId });
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        // GET: Donation/Edit/5
        //UPDATED CODE to get the event id to edit although I dont think event id needs to be edited as anything with money should not be edit not sure how to lock that down
        public ActionResult Edit(int id)
        {
            //add n the new view model and create a new instance of it 
            UpdateDonation ViewModel = new UpdateDonation();
            //starting with the url string REFERENCES:varsity MVP for this code and inclass live example
            //this is where I had issues in my passion project!!!! (Mind blown)
            string url = "DonationData/FindDonation/" + id;
            //reusing code from "Find Donation By Id".
            HttpResponseMessage response = client.GetAsync(url).Result;

            // The http call worked.
            if (response.IsSuccessStatusCode)
            {
                DonationDto Selecteddonation = response.Content.ReadAsAsync<DonationDto>().Result;
                ViewModel.donation = Selecteddonation;

                //adding in event id 
                //REUSING CODE FROM create donation 
                //url : from AMANDA's DATA CONTROLLER
                url = "EventData/GetEvents";
                response = client.GetAsync(url).Result;
                IEnumerable<EventDto> PotentialEvents = response.Content.ReadAsAsync<IEnumerable<EventDto>>().Result;
                ViewModel.allevents = PotentialEvents;

                return View(ViewModel);

            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        // POST: Donation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Donation donationInfo)
        {
            string url = "DonationData/UpdateDonation/" + id;

            Debug.WriteLine(jss.Serialize(donationInfo));
            HttpContent content = new StringContent(jss.Serialize(donationInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                //redirect to details page for the user to view the details that have been updated 
                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }


        }

        // GET: Donation/Delete/5
        //PROCESS:: first get the dontaion by id -> confirm the delete ->then delete the choosen donation and redirect to new list page without the donation
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "DonationData/FindDonation/" + id;
            //sending HTTP request 
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                DonationDto Selecteddonation = response.Content.ReadAsAsync<DonationDto>().Result;
                return View(Selecteddonation);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Donation/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "DonationData/DeleteDonation/" + id;

            //no new Http content to be displayed here
            HttpContent content = new StringContent("");
            //Sending reponse request 
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            //if successful return the user to List view with the update list..else error
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
    }
}

Manitouage1/Views/Donation/Create.cshtml
@model Manitouage1.Models.ViewModels.CreateDonation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Make a Donation</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.donation.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.EventId, "Events", htmlAttributes: new { @class = "control-label col-md-2",})
            <div class="col-md-10">
                <!--REFERENCE CODE:: varsity with auth player create view-->
                <!--in create view-->
                <select name="donation.EventId">
                    @foreach (var Event in Model.allevents)
                    {
                        <option value="@Event.EventId">
                            @Event.Title
                        </option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Manitouage1/Views/Donation/DeleteConfirm.cshtml
@model Manitouage1.Models.DonationDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Donation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Donation", new { id = Model.donationId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

Manitouage1/Views/Donation/Details.cshtml
@model Manitouage1.Models.ViewModels.ShowDonation
<!--admin functionality wont need layout -->
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Donation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.events.Title)
        </dt>

        <dd><!--NOT SHOWING!!! -->
            @Html.DisplayFor(model => model.events.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donation.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donation.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donation.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donation.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donation.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donation.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donation.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donation.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donation.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donation.amount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.donation.donationId }) |
    @Html.ActionLink("Back to List", "List")
</p>

Manitouage1/Views/Donation/Edit.cshtml
@model Manitouage1.Models.ViewModels.UpdateDonation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


<!--just added to see if this works-->
@using (Html.BeginForm("Edit", "Donation", FormMethod.Post, new { id = Model.donation.donationId }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Donation</h4>
        <hr />
        <!--validation already done-->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--edited existing code with adding donation table (MAKE SURE IT IS THE SAME AS THE VIEW MODEL) then grabing the column-->
        @Html.HiddenFor(model => model.donation.donationId)

        <div class="form-group">
            @Html.LabelFor(model => model.donation.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donation.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donation.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donation.EventId, "Events", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!--REFERENCE CODE:: varsity with auth player create view-->
                <!--in edit view event id needs to match donation event id-->
                <select name="EventId">
                    @foreach (var Event in Model.allevents)
                    {
                        <option value="@Event.EventId"
                                @if (Event.EventId == Model.donation.EventId) { <text> selected</text>}>
                            @Event.Title
                        </option>
                    }
                </select>
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        }
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Manitouage1/Views/Donation/List.cshtml
@model Manitouage1.Models.ViewModels.ListDonation

@{
    ViewBag.Title = "List";
    //added in layout THIS WAS ALL SANDRA!!!! 
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Donations</h2>
<!--only for admin view-->

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <!--add in if statment if it is admin-->
        <!--help from miho-->
        <th>
            @Html.DisplayNameFor(model => model.Event.Title)
        </th>
        <th>
           First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th>
            Phone Number
        </th>
        <th>
            Donation Amount
        </th>
        <th></th>
    </tr>
    <!--add the view model all donations-->
@foreach (var item in Model.alldonations) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.donationId }) |
            @Html.ActionLink("Details", "Details", new { id=item.donationId }) |
            @Html.ActionLink("Delete", "DeleteConfirm", new { id=item.donationId })
        </td>
    </tr>
}

</table>