Manitouage1/Models/Volunteer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manitouage1.Models
{
    public class Volunteer
    {
        [Key]
        public int volunteerId { get; set; }

        [Required]
        public string firstName { get; set; }

        [Required]
        public string lastName { get; set; }

        [Required]
        public bool policeCheckPass { get; set; }

        [Required]
        public string email { get; set; }

        [Required]
        public string phone { get; set; }

        [Required]
        public bool approved { get; set; }

        [AllowHtml]
        [Required]
        public string survey { get; set; }

        [ForeignKey("Event")]
        public int? EventId { get; set; }
        public Event Event { get; set; }

    }

    public class VolunteerDto
    {
        [DisplayName("Volunteer ID")]
        public int volunteerId { get; set; }

        [DisplayName("First Name")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [DisplayName("Police Check Pass")]
        public bool policeCheckPass { get; set; }

        [DisplayName("Email")]
        public string email { get; set; }

        [DisplayName("Phone")]
        public string phone { get; set; }

        [DisplayName("Approved")]
        public bool approved { get; set; }

        [DisplayName("EventId")]
        public int? EventId { get; set; }


    }
}

Manitouage1/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Manitouage1.Models;
using System.Web.Script.Serialization;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;

namespace Manitouage1.Controllers
{
    public class VolunteerController : Controller

    {

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;

        static VolunteerController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                //cookies are manually set in RequestHeader
                UseCookies = false
            };

            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44397/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }


        // GET: Volunteer
        // Lists all events that require volunteers
        public ActionResult Index()
        {
            // get list of events
            string url = "eventdata/getevents";
            HttpResponseMessage res = client.GetAsync(url).Result;
            if (res.IsSuccessStatusCode)
            {
                IEnumerable<EventDto> EventDtos = res.Content.ReadAsAsync<IEnumerable<EventDto>>().Result;
                return View(EventDtos);
            }
            return View();
        }

        // GET: List all volunteer applications
        // only admin can see the list of volunteers
        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            //List<VolunteerDto> Volunteers = new List<VolunteerDto>();

            string url = "volunteerdata/getvolunteers";

            HttpResponseMessage res = client.GetAsync(url).Result;

            if (res.IsSuccessStatusCode)
            {
                IEnumerable<VolunteerDto> VolunteerDtos = res.Content.ReadAsAsync<IEnumerable<VolunteerDto>>().Result;


                return View(VolunteerDtos);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: View for volunteer application. 
        // TODO figure out how to handle policecheck (maybe file upload then admin update?)
        public ActionResult Create(int? id)
        {
            string url = "eventdata/getevent/" + id;
            HttpResponseMessage res = client.GetAsync(url).Result;

            // event exists
            if (res.IsSuccessStatusCode)
            {
                ViewBag.eventId = id;
                return View();
            }

            ViewBag.eventId = null;
            return View();
        }

        // POST : bind volunteer model to form post
        // TODO: create some screening questions for the application
        // TODO: add validation to create form
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Volunteer Volunteer)
        {

            string url = "volunteerdata/addvolunteer";
            HttpContent content = new StringContent(jss.Serialize(Volunteer));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage res = client.PostAsync(url, content).Result;

            if (res.IsSuccessStatusCode)
            {
                // List is essentially admin dashboard
                if (User.IsInRole("Admin")) {
                    return RedirectToAction("List");
                }

                return RedirectToAction("ConfirmApplication");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        public ActionResult Edit(int id)
        {
            string url = "volunteerdata/findvolunteer/" + id;
            HttpResponseMessage res = client.GetAsync(url).Result;

            if (res.IsSuccessStatusCode)
            {
                VolunteerDto VolunteerDto = res.Content.ReadAsAsync<VolunteerDto>().Result;
                return View(VolunteerDto);
            }
            return RedirectToAction("Error");
        }

        public ActionResult DeleteConfirm(int id)
        {
            string url = "volunteerdata/findvolunteer/" + id;
            HttpResponseMessage res = client.GetAsync(url).Result;

            if (res.IsSuccessStatusCode)
            {
                VolunteerDto VolunteerDto = res.Content.ReadAsAsync<VolunteerDto>().Result;
                return View(VolunteerDto);
            }
            return RedirectToAction("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "volunteerdata/deletevolunteer/" + id;
            HttpContent content = new StringContent("");
            HttpResponseMessage res = client.PostAsync(url, content).Result;

            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Error");
        }

        public ActionResult ApproveConfirm(int id)
        {
            string url = "volunteerdata/findvolunteer/" + id;
            HttpResponseMessage res = client.GetAsync(url).Result;

            if (res.IsSuccessStatusCode)
            {
                VolunteerDto VolunteerDto = res.Content.ReadAsAsync<VolunteerDto>().Result;
                return View(VolunteerDto);
            }
            return RedirectToAction("Error");
        }


        [HttpPost]
        public ActionResult Approve(int id)
        {
            string url = "volunteerdata/approvevolunteer/" + id;
            HttpContent content = new StringContent("");
            HttpResponseMessage res = client.PostAsync(url, content).Result;

            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Error");
        }

        public ActionResult ConfirmApplication()
        {
            return View();
        }

        // GET: Volunteer/Error
        public ActionResult Error()
        {
            return View();
        }
    }
}

Manitouage1/Views/Volunteer/ApproveConfirm.cshtml
@model Manitouage1.Models.VolunteerDto

@{
    ViewBag.Title = "ApproveConfirm";
}

<h1>Are you sure you want to Approve</h1>
<div>
    <h4>Volunteer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.policeCheckPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.policeCheckPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.approved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.approved)
        </dd>

    </dl>
</div>
@using (Html.BeginForm("Approve", "Volunteer", new { id = Model.volunteerId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Approve" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "List")
    </div>
}

Manitouage1/Views/Volunteer/ConfirmApplication.cshtml
@{
    ViewBag.Title = "ConfirmApplication";
}

<h2>Successfully Applied!</h2>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Manitouage1/Views/Volunteer/Create.cshtml
@model Manitouage1.Models.Volunteer

@{
    ViewBag.Title = "Create";
}

<h2>Volunteer Application</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, "Phone Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.survey, "Why do you want to volunteer?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.survey, htmlAttributes: new { @class = "form-control admin" } )
                @Html.ValidationMessageFor(model => model.survey, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- new volunteers are default not approved -->
        @Html.HiddenFor(model => model.approved, new { Value = false })
        <!-- new volunteers are default not police checked-->
        @Html.HiddenFor(model => model.policeCheckPass, new { Value = false })
        <!-- eventId -->
        @Html.HiddenFor(model => model.EventId, new { Value = ViewBag.EventId })


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Apply" class="btn btn-default btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Manitouage1/Views/Volunteer/DeleteConfirm.cshtml
@model Manitouage1.Models.VolunteerDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h1>Are you sure you want to Delete</h1>
<div>
    <h4>Volunteer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.policeCheckPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.policeCheckPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.approved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.approved)
        </dd>

    </dl>
</div>
@using (Html.BeginForm("Delete", "Volunteer", new { id = Model.volunteerId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "List")
    </div>
}

Manitouage1/Views/Volunteer/Edit.cshtml
@model Manitouage1.Models.VolunteerDto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Volunteer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.volunteerId)

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.policeCheckPass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.policeCheckPass)
                    @Html.ValidationMessageFor(model => model.policeCheckPass, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.approved)
                    @Html.ValidationMessageFor(model => model.approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Manitouage1/Views/Volunteer/Index.cshtml
@model IEnumerable<Manitouage1.Models.EventDto>
@{
    ViewBag.Title = "Index";
}

<h2>Events currently looking for volunteers</h2>

@foreach (var e in Model)
{
<div>
    <h3>Event: @e.Title</h3>
    <p>Description: @e.Description</p>
    <p>Date: @e.DateTime</p>
    <p>Location: @e.Location</p>
    <p>Main Contact: @e.ContactPerson</p>
    <p>@Html.ActionLink("Volunteer Now", "Create", "Volunteer", new { id = e.EventId }, new { @class ="btn btn-primary"})</p>
</div>
}

Manitouage1/Views/Volunteer/List.cshtml
@model IEnumerable<Manitouage1.Models.VolunteerDto>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.policeCheckPass)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.approved)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.policeCheckPass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.approved)
            </td>
            <td>
                @Html.ActionLink("View", "Edit", new { id = item.volunteerId }) |
                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.volunteerId }) |
                @Html.ActionLink("Approve", "ApproveConfirm", new { id = item.volunteerId })
            </td>
        </tr>
    }

</table>